### ISSUE TITLE
Script terminates at the feature file function 

### ISSUE THREAD

**Issue by mzywj2** [slimsuite/chromsyn#5]
Hi,

An error appears for the feature file as shown in the image I have attached. To see if it would move forward I added a ft.fofn empty file but there is no difference. Does the script require GFF files converted to tsv and a ft.fofn for those files? I'm currently running augustus on my fastas and converting the gff to tsv to see if this will solve the issue, but a little confused since the test run dataset or the guidelines don't mention the need for such a file. 

Thank you
![Screenshot 2024-06-06 152255](https://github.com/slimsuite/chromsyn/assets/151543153/d8c971fc-8e60-4b53-aea4-87ef1807b7fb)

**Comment by slimsuite** [comment]
Hi. I'd like to help you solve this but I need more information about how you are trying to run it and what the input files look like. It shouldn't need a ft.fofn file to run. It looks like the current error is being caused by the fofn file having the wrong format. Every `*.fofn` file needs two columns: the genome alias, and the corresponding file path.

**Comment by mzywj2** [comment]
Hi,

Thank you for getting back to me. I'm running the script on the R terminal using Rscript chromsyn.R

I've added a feature and ft.fofn file as well and the script now runs till the end but I get a different error now (image attached)

The input file names are attached in a image as well, and the fofn files are also attached.

Please let me know if you would like any more of the input files?

Kind Regards
________________________________

**Comment by mzywj2** [comment]
Hi,

I'll also copy the full output I get in the terminal when I run the script.

Thank you
________________________________

**Comment by slimsuite** [comment]
Can you check whether the first genes in the BUSCO file(s) are rated as Missing? Probably the C_officinalis results, given it's low Completeness. If so, then removing these genes or moving one of the Fragmented/Complete ones to the top should fix the issue. (I can't remember if I fixed this bug or not.)

**Comment by mzywj2** [comment]
Hi,

Yes the first gene in both the C_officinalis and the Cexcelsa_scaf_1 buscos are rated missing, I removed the the first gene which was rated as missing (attached the busco files with the missing first gene removed) however, I'm still getting the same error that:
Error in `$<-.data.frame`(`*tmp*`, Strand, value = "-") :
  replacement has 1 row, data has 0
Calls: $<- -> $<-.data.frame
Execution halted

Is there anything else I can do to remove this error and get an output?

Thank you
________________________________

**Comment by slimsuite** [comment]
Just to clarify... you removed all the Missing genes until you reached a not-Missing one?

The easiest thing might be to email me your input files (rich.edwards@uwa.edu.au) and I will see if I can recreate the error. I don't think attachments from the emails get attached to the issue on GitHub.

**Comment by slimsuite** [comment]
I received your email. I will take a look.

**Comment by mzywj2** [comment]
Thank you so much!
________________________________

**Comment by mzywj2** [comment]
Hi,

I understand you might be busy, but just wondering if there's any update on the error.

Thank you
________________________________

**Comment by slimsuite** [comment]
Hi,
I made new FOFN files and it ran fine. I will send you an email now with the files and command I used. Looks like you might have a ployploidy with C_officinalis so I will send a suggestion for exploring this too, in case it is useful.
Rich

**Comment by slimsuite** [comment]
PS. I ran it with the full BUSCO file ("with_missing") and it was fine, so this was not an issue.
PPS. I note that there are a LOT of features in the features TSV file - 455,115 in total. I am not sure what these are, but having this many might cause issues and certainly won't plot in a useful way. I'd recommend running without the `ft.fofn` file.
